# Generated by Django 4.2.7 on 2023-11-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_bird_delete_cat_delete_dog_alter_profile_dob'),
    ]


