# Generated by Django 4.2.7 on 2023-11-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_bird_delete_cat_delete_dog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_num',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(default='', max_length=200),
        ),
    ]
