# Generated by Django 4.2.7 on 2023-11-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_bird_delete_cat_delete_dog_alter_profile_dob_and_more'),
    ]

    operations = [
    ]
