# Generated by Django 4.2.7 on 2023-11-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_messages_delete_bird_delete_cat_delete_dog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='message_content',
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='main_app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='sender_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='main_app.profile'),
            preserve_default=False,
        ),
    ]
