# Generated by Django 4.2.7 on 2023-11-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_delete_bird_delete_cat_delete_dog'),
    ]

    operations = [
    ]
