# Generated by Django 4.2.7 on 2023-11-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_delete_bird_delete_cat_delete_dog_profile_user'),
    ]

    operations = [

    ]
