# Generated by Django 4.2.7 on 2023-11-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_delete_bird_delete_cat_delete_dog_remove_media_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_profile', to='main_app.profile')),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to='main_app.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
