# Generated by Django 4.2.7 on 2023-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0021_delete_bird_delete_cat_delete_dog_and_more'),
    ],
    operations = [
        migrations.AlterField(
            model_name='media',
            name='document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
