# Generated by Django 4.2.7 on 2023-11-23 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_delete_bird_delete_cat_delete_dog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='Feed',
        ),
        migrations.RemoveField(
            model_name='media',
            name='likes',
        ),
        migrations.AddField(
            model_name='likes',
            name='Media',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.media'),
            preserve_default=False,
        ),
    ]
