# Generated by Django 4.2.7 on 2023-11-23 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_delete_bird_delete_cat_delete_dog_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='likes',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
            preserve_default=False,
        ),
    ]
